### ISSUE TITLE
用cocoapod安装一直卡在Installling那里

### ISSUE THREAD

**Issue by sabertoothPaste** [beecloud/beecloud-ios#46]
1. 环境, macOs Sierra, Xcode 8.0 cocoapod 1.1.1 
其他库安装正常

**Comment by sabertoothPaste** [comment]
cocoapod 配置问题已解决

**Comment by gcbpay** [comment]
有任何技术疑难问题可直接添加RIpple核心开发工程师微信咨询探讨：微信号：lzxjcyx
