### ISSUE TITLE
Cocoapods集成时和UTDID框架有冲突.

### ISSUE THREAD

**Issue by sabertoothPaste** [beecloud/beecloud-ios#47]
集成的AlipaySDK 内部包含了UTDID , 和百川反馈专业版依赖的UTDID有冲突.
官方出了剥离了UTDID的版本, 在这里
https://doc.open.alipay.com/doc2/detail.htm?treeId=54&articleId=104509&docType=1

**Comment by Ewenlong03** [comment]
您可以用支付宝提供的剥离了UTDID的版本，替换掉我们SDK里面的AlipaySDK

**Comment by sabertoothPaste** [comment]
那每次Pod update的时候都要替换吗

**Comment by Ewenlong03** [comment]
目前你先这样解决吧，最近我们更新下版本，新增一个alipay的source吧

**Comment by sabertoothPaste** [comment]
已经替换了, pod install 暂时没有问题.
