### ISSUE TITLE
TMS-90809: Deprecated API Usage 

### ISSUE THREAD

**Issue by Iamivan1996** [beecloud/beecloud-ios#56]
Apple will stop accepting submissions of apps that use UIWebView APIs starting from April 2020

**Comment by HHuiHao** [comment]
作者能抽时间替换掉UIWebView，苹果不再支持UIWebView了？

**Comment by Iamivan1996** [comment]
@HHuiHao  作者，官方的客服和技術人員大概是不會再出現的了哈哈哈，我也是自己發現問題的根源再根治，問題發生在beecloud 引用的wechat 和alipay版本太舊了, 替換新的就解決了
